package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/dani-zion/ganja-livre/internal/graph/generated"
	"github.com/dani-zion/ganja-livre/internal/graph/model"
	"github.com/dani-zion/ganja-livre/internal/middleware"
	dbmodel "github.com/dani-zion/ganja-livre/internal/model"
	"github.com/dani-zion/ganja-livre/internal/temporal/workflows"
	"github.com/dani-zion/ganja-livre/internal/validator"
	"github.com/google/uuid"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go.temporal.io/sdk/client"
	"golang.org/x/crypto/bcrypt"
)

// Register new users.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	input.Email = strings.TrimSpace(input.Email)
	input.Name = strings.TrimSpace(input.Name)
	if input.Email == "" || input.Password == "" || input.Name == "" {
		return nil, fmt.Errorf("email, password, and name are required")
	}
	if len(input.Password) < 8 {
		return nil, fmt.Errorf("password must be at least 8 characters")
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, errInternal
	}
	roles := input.Roles
	if len(roles) == 0 {
		roles = []model.UserRole{model.UserRoleCustomer}
	}
	now := time.Now().UTC()
	user := dbmodel.User{
		ID:           primitive.NewObjectID(),
		Email:        input.Email,
		PasswordHash: string(hash),
		Name:         input.Name,
		Roles:        toDBRoles(roles),
		IsActive:     true,
		CreatedAt:    now,
		UpdatedAt:    now,
	}
	_, err = r.cols.Users.InsertOne(ctx, user)
	if err != nil {
		if mongo.IsDuplicateKeyError(err) {
			return nil, errEmailTaken
		}
		return nil, errInternal
	}
	tokens, err := r.jwtSvc.IssueTokenPair(user.ID.Hex(), user.Email, roles)
	if err != nil {
		return nil, errInternal
	}
	return &model.AuthPayload{
		AccessToken:  tokens.AccessToken,
		RefreshToken: tokens.RefreshToken,
		User: &model.User{
			ID:        user.ID.Hex(),
			Email:     user.Email,
			Name:      user.Name,
			Roles:     roles,
			CreatedAt: user.CreatedAt,
			UpdatedAt: user.UpdatedAt,
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	input.Email = strings.TrimSpace(input.Email)
	if input.Email == "" || input.Password == "" {
		return nil, fmt.Errorf("email and password are required")
	}
	var user dbmodel.User
	err := r.cols.Users.FindOne(ctx, bson.M{"email": input.Email}).Decode(&user)
	if err == mongo.ErrNoDocuments {
		return nil, errInvalidCredentials
	}
	if err != nil {
		return nil, errInternal
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.PasswordHash), []byte(input.Password)); err != nil {
		return nil, errInvalidCredentials
	}
	roles := toGraphRoles(user.Roles)
	tokens, err := r.jwtSvc.IssueTokenPair(user.ID.Hex(), user.Email, roles)
	if err != nil {
		return nil, errInternal
	}
	return &model.AuthPayload{
		AccessToken:  tokens.AccessToken,
		RefreshToken: tokens.RefreshToken,
		User: &model.User{
			ID:        user.ID.Hex(),
			Email:     user.Email,
			Name:      user.Name,
			Roles:     roles,
			CreatedAt: user.CreatedAt,
			UpdatedAt: user.UpdatedAt,
		},
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.AuthPayload, error) {
	claims, err := r.jwtSvc.ValidateRefreshToken(token)
	if err != nil {
		return nil, errInvalidToken
	}
	uid, err := primitive.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, errInvalidToken
	}
	var user dbmodel.User
	err = r.cols.Users.FindOne(ctx, bson.M{"_id": uid}).Decode(&user)
	if err == mongo.ErrNoDocuments {
		return nil, errNotFound
	}
	if err != nil {
		return nil, errInternal
	}
	if !user.IsActive {
		return nil, errInvalidToken
	}
	roles := toGraphRoles(user.Roles)
	tokens, err := r.jwtSvc.IssueTokenPair(user.ID.Hex(), user.Email, roles)
	if err != nil {
		return nil, errInternal
	}
	return &model.AuthPayload{
		AccessToken:  tokens.AccessToken,
		RefreshToken: tokens.RefreshToken,
		User: &model.User{
			ID:        user.ID.Hex(),
			Email:     user.Email,
			Name:      user.Name,
			Roles:     roles,
			CreatedAt: user.CreatedAt,
			UpdatedAt: user.UpdatedAt,
		},
	}, nil
}

// BecomeSeller adds the SELLER role to the authenticated user.
func (r *mutationResolver) BecomeSeller(ctx context.Context) (*model.User, error) {
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	uid, err := primitive.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, errNotFound
	}
	var user dbmodel.User
	err = r.cols.Users.FindOne(ctx, bson.M{"_id": uid}).Decode(&user)
	if err == mongo.ErrNoDocuments {
		return nil, errNotFound
	}
	if err != nil {
		return nil, errInternal
	}
	for _, role := range user.Roles {
		if role == dbmodel.RoleSeller {
			roles := toGraphRoles(user.Roles)
			return &model.User{
				ID:        user.ID.Hex(),
				Email:     user.Email,
				Name:      user.Name,
				Roles:     roles,
				CreatedAt: user.CreatedAt,
				UpdatedAt: user.UpdatedAt,
			}, nil
		}
	}
	newRoles := append(user.Roles, dbmodel.RoleSeller)
	now := time.Now().UTC()
	_, err = r.cols.Users.UpdateOne(ctx,
		bson.M{"_id": uid},
		bson.M{"$set": bson.M{"roles": newRoles, "updated_at": now}},
	)
	if err != nil {
		return nil, errInternal
	}
	user.Roles = newRoles
	user.UpdatedAt = now
	roles := toGraphRoles(user.Roles)
	return &model.User{
		ID:        user.ID.Hex(),
		Email:     user.Email,
		Name:      user.Name,
		Roles:     roles,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
	}, nil
}

// StopSelling removes the SELLER role from the authenticated user.
func (r *mutationResolver) StopSelling(ctx context.Context) (*model.User, error) {
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	uid, err := primitive.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, errNotFound
	}
	var user dbmodel.User
	err = r.cols.Users.FindOne(ctx, bson.M{"_id": uid}).Decode(&user)
	if err == mongo.ErrNoDocuments {
		return nil, errNotFound
	}
	if err != nil {
		return nil, errInternal
	}
	var newRoles []dbmodel.UserRole
	for _, role := range user.Roles {
		if role != dbmodel.RoleSeller {
			newRoles = append(newRoles, role)
		}
	}
	if len(newRoles) == 0 {
		newRoles = []dbmodel.UserRole{dbmodel.RoleCustomer}
	}
	now := time.Now().UTC()
	_, err = r.cols.Users.UpdateOne(ctx,
		bson.M{"_id": uid},
		bson.M{"$set": bson.M{"roles": newRoles, "updated_at": now}},
	)
	if err != nil {
		return nil, errInternal
	}
	user.Roles = newRoles
	user.UpdatedAt = now
	roles := toGraphRoles(user.Roles)
	return &model.User{
		ID:        user.ID.Hex(),
		Email:     user.Email,
		Name:      user.Name,
		Roles:     roles,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
	}, nil
}

// CreateProduct allows sellers and admins to add products.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	claims, err := middleware.RequireRole(ctx, model.UserRoleSeller, model.UserRoleAdmin)
	if err != nil {
		return nil, err
	}
	if err = validator.Price(input.Price); err != nil {
		return nil, err
	}
	if err = validator.Stock(input.Stock); err != nil {
		return nil, err
	}
	if input.ThcContent != nil {
		if err = validator.PercentContent(*input.ThcContent, "thcContent"); err != nil {
			return nil, err
		}
	}
	sellerID, _ := primitive.ObjectIDFromHex(claims.UserID)
	now := time.Now().UTC()
	dbProduct := dbmodel.Product{
		ID:          primitive.NewObjectID(),
		Name:        input.Name,
		Description: input.Description,
		Category:    dbmodel.ProductCategory(input.Category),
		Price:       input.Price,
		Stock:       input.Stock,
		THCContent:  input.ThcContent,
		CBDContent:  input.CbdContent,
		Strain:      input.Strain,
		Origin:      input.Origin,
		ImageURLs:   input.ImageURLs,
		SellerID:    sellerID,
		IsActive:    true,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	if _, err = r.cols.Products.InsertOne(ctx, dbProduct); err != nil {
		return nil, errInternal
	}
	return &model.Product{
		ID:          dbProduct.ID.Hex(),
		Name:        dbProduct.Name,
		Description: dbProduct.Description,
		Category:    model.ProductCategory(dbProduct.Category),
		Price:       dbProduct.Price,
		Stock:       dbProduct.Stock,
		ThcContent:  dbProduct.THCContent,
		CbdContent:  dbProduct.CBDContent,
		Strain:      dbProduct.Strain,
		Origin:      dbProduct.Origin,
		ImageURLs:   dbProduct.ImageURLs,
		SellerID:    dbProduct.SellerID.Hex(),
		IsActive:    dbProduct.IsActive,
		CreatedAt:   dbProduct.CreatedAt,
		UpdatedAt:   dbProduct.UpdatedAt,
	}, nil
}

// UpdateProduct lets sellers edit their own products; admins can edit any.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	claims, err := middleware.RequireRole(ctx, model.UserRoleSeller, model.UserRoleAdmin)
	if err != nil {
		return nil, err
	}
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, errNotFound
	}
	filter := bson.M{"_id": oid}
	if !hasRole(claims.Roles, model.UserRoleAdmin) {
		sellerID, _ := primitive.ObjectIDFromHex(claims.UserID)
		filter["seller_id"] = sellerID
	}
	set := bson.M{"updated_at": time.Now().UTC()}
	if input.Name != nil {
		set["name"] = *input.Name
	}
	if input.Description != nil {
		set["description"] = *input.Description
	}
	if input.Price != nil {
		if err = validator.Price(*input.Price); err != nil {
			return nil, err
		}
		set["price"] = *input.Price
	}
	if input.Stock != nil {
		if err = validator.Stock(*input.Stock); err != nil {
			return nil, err
		}
		set["stock"] = *input.Stock
	}
	if input.IsActive != nil {
		set["is_active"] = *input.IsActive
	}
	if input.ImageURLs != nil {
		set["image_urls"] = input.ImageURLs
	}
	after := options.After
	opts := options.FindOneAndUpdate().SetReturnDocument(after)
	var updated dbmodel.Product
	if err = r.cols.Products.FindOneAndUpdate(ctx, filter, bson.M{"$set": set}, opts).Decode(&updated); err != nil {
		return nil, errNotFound
	}
	return &model.Product{
		ID:          updated.ID.Hex(),
		Name:        updated.Name,
		Description: updated.Description,
		Category:    model.ProductCategory(updated.Category),
		Price:       updated.Price,
		Stock:       updated.Stock,
		ThcContent:  updated.THCContent,
		CbdContent:  updated.CBDContent,
		Strain:      updated.Strain,
		Origin:      updated.Origin,
		ImageURLs:   updated.ImageURLs,
		SellerID:    updated.SellerID.Hex(),
		IsActive:    updated.IsActive,
		CreatedAt:   updated.CreatedAt,
		UpdatedAt:   updated.UpdatedAt,
	}, nil
}

// DeleteProduct soft-deletes (deactivates) a product.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	claims, err := middleware.RequireRole(ctx, model.UserRoleSeller, model.UserRoleAdmin)
	if err != nil {
		return false, err
	}
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return false, errNotFound
	}
	filter := bson.M{"_id": oid}
	if !hasRole(claims.Roles, model.UserRoleAdmin) {
		sellerID, _ := primitive.ObjectIDFromHex(claims.UserID)
		filter["seller_id"] = sellerID
	}
	res, err := r.cols.Products.UpdateOne(ctx, filter,
		bson.M{"$set": bson.M{"is_active": false, "updated_at": time.Now().UTC()}},
	)
	if err != nil {
		return false, errInternal
	}
	return res.MatchedCount > 0, nil
}

// PlaceOrder creates an order and kicks off the Temporal workflow.
func (r *mutationResolver) PlaceOrder(ctx context.Context, input model.PlaceOrderInput) (*model.Order, error) {
	claims, err := middleware.RequireRole(ctx, model.UserRoleCustomer, model.UserRoleAdmin)
	if err != nil {
		return nil, err
	}
	if len(input.Items) == 0 {
		return nil, fmt.Errorf("order must contain at least one item")
	}
	buyerID, _ := primitive.ObjectIDFromHex(claims.UserID)
	var orderItems []dbmodel.OrderItem
	var totalAmount float64
	var workflowItems []workflows.OrderItemInput
	for _, item := range input.Items {
		if err = validator.Quantity(item.Quantity); err != nil {
			return nil, err
		}
		pid, err := primitive.ObjectIDFromHex(item.ProductID)
		if err != nil {
			return nil, fmt.Errorf("invalid product id: %s", item.ProductID)
		}
		var product dbmodel.Product
		if err = r.cols.Products.FindOne(ctx, bson.M{"_id": pid, "is_active": true}).Decode(&product); err != nil {
			return nil, fmt.Errorf("product not found: %s", item.ProductID)
		}
		subtotal := product.Price * float64(item.Quantity)
		orderItems = append(orderItems, dbmodel.OrderItem{
			ProductID: pid,
			Quantity:  item.Quantity,
			UnitPrice: product.Price,
			Subtotal:  subtotal,
		})
		totalAmount += subtotal
		workflowItems = append(workflowItems, workflows.OrderItemInput{
			ProductID: item.ProductID,
			Quantity:  item.Quantity,
		})
	}
	workflowID := fmt.Sprintf("order-%s", uuid.New().String())
	now := time.Now().UTC()
	order := dbmodel.Order{
		ID:                 primitive.NewObjectID(),
		BuyerID:            buyerID,
		Items:              orderItems,
		TotalAmount:        totalAmount,
		Status:             dbmodel.StatusPending,
		ShippingAddress:    toDBAddress(input.ShippingAddress),
		TemporalWorkflowID: workflowID,
		CreatedAt:          now,
		UpdatedAt:          now,
	}
	if _, err = r.cols.Orders.InsertOne(ctx, order); err != nil {
		return nil, errInternal
	}
	_, err = r.temporal.ExecuteWorkflow(ctx,
		client.StartWorkflowOptions{
			ID:        workflowID,
			TaskQueue: workflows.TaskQueueName,
		},
		"OrderWorkflow",
		workflows.OrderWorkflowInput{
			OrderID: order.ID.Hex(),
			BuyerID: claims.UserID,
			Amount:  totalAmount,
			Items:   workflowItems,
		},
	)
	if err != nil {
		_, _ = r.cols.Orders.DeleteOne(ctx, bson.M{"_id": order.ID})
		return nil, fmt.Errorf("failed to start order workflow: %w", err)
	}
	orders, err := r.toGraphOrders(ctx, []dbmodel.Order{order})
	if err != nil {
		return nil, err
	}
	return orders[0], nil
}

// CancelOrder sends a cancellation signal to the running workflow.
func (r *mutationResolver) CancelOrder(ctx context.Context, id string) (*model.Order, error) {
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, errNotFound
	}
	filter := bson.M{"_id": oid}
	if hasRole(claims.Roles, model.UserRoleCustomer) && !hasRole(claims.Roles, model.UserRoleAdmin) {
		buyerID, _ := primitive.ObjectIDFromHex(claims.UserID)
		filter["buyer_id"] = buyerID
	}
	var order dbmodel.Order
	if err = r.cols.Orders.FindOne(ctx, filter).Decode(&order); err != nil {
		return nil, errNotFound
	}
	if order.Status != dbmodel.StatusPending && order.Status != dbmodel.StatusPaymentProcessing {
		return nil, fmt.Errorf("order cannot be cancelled in status: %s", order.Status)
	}
	if err = r.temporal.SignalWorkflow(ctx,
		order.TemporalWorkflowID, "",
		workflows.SignalOrderCancelled, nil,
	); err != nil {
		return nil, fmt.Errorf("failed to send cancellation signal: %w", err)
	}
	return r.singleOrder(ctx, order)
}

// UpdateOrderStatus is an admin operation.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status model.OrderStatus) (*model.Order, error) {
	if _, err := middleware.RequireRole(ctx, model.UserRoleAdmin); err != nil {
		return nil, err
	}
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, errNotFound
	}
	now := time.Now().UTC()
	after := options.After
	opts := options.FindOneAndUpdate().SetReturnDocument(after)
	var updated dbmodel.Order
	if err = r.cols.Orders.FindOneAndUpdate(ctx,
		bson.M{"_id": oid},
		bson.M{"$set": bson.M{"status": string(status), "updated_at": now}},
		opts,
	).Decode(&updated); err != nil {
		return nil, errNotFound
	}
	return r.singleOrder(ctx, updated)
}

// Products lists active products with optional filtering and cursor-based pagination.
func (r *queryResolver) Products(ctx context.Context, filter *model.ProductFilterInput, first *int, after *string) (*model.ProductConnection, error) {
	query := bson.M{"is_active": true}
	if filter != nil {
		if filter.Category != nil {
			query["category"] = *filter.Category
		}
		priceFilter := bson.M{}
		if filter.MinPrice != nil {
			priceFilter["$gte"] = *filter.MinPrice
		}
		if filter.MaxPrice != nil {
			priceFilter["$lte"] = *filter.MaxPrice
		}
		if len(priceFilter) > 0 {
			query["price"] = priceFilter
		}
		if filter.Search != nil && *filter.Search != "" {
			query["$text"] = bson.M{"$search": *filter.Search}
		}
	}
	if after != nil && *after != "" {
		cursorID, err := primitive.ObjectIDFromHex(*after)
		if err == nil {
			query["_id"] = bson.M{"$gt": cursorID}
		}
	}
	limit := int64(defaultPageSize)
	if first != nil && *first > 0 && *first <= 100 {
		limit = int64(*first)
	}
	findOpts := options.Find().
		SetLimit(limit + 1).
		SetSort(bson.D{{Key: "_id", Value: 1}})
	cursor, err := r.cols.Products.Find(ctx, query, findOpts)
	if err != nil {
		return nil, errInternal
	}
	defer cursor.Close(ctx)
	var dbProducts []dbmodel.Product
	if err = cursor.All(ctx, &dbProducts); err != nil {
		return nil, errInternal
	}
	hasNext := len(dbProducts) > int(limit)
	if hasNext {
		dbProducts = dbProducts[:limit]
	}
	edges := make([]*model.ProductEdge, len(dbProducts))
	for i, p := range dbProducts {
		product := model.Product{
			ID:          p.ID.Hex(),
			Name:        p.Name,
			Description: p.Description,
			Category:    model.ProductCategory(p.Category),
			Price:       p.Price,
			Stock:       p.Stock,
			ThcContent:  p.THCContent,
			CbdContent:  p.CBDContent,
			Strain:      p.Strain,
			Origin:      p.Origin,
			ImageURLs:   p.ImageURLs,
			SellerID:    p.SellerID.Hex(),
			IsActive:    p.IsActive,
			CreatedAt:   p.CreatedAt,
			UpdatedAt:   p.UpdatedAt,
		}
		edges[i] = &model.ProductEdge{Node: &product, Cursor: p.ID.Hex()}
	}
	var startCursor, endCursor *string
	if len(edges) > 0 {
		s := edges[0].Cursor
		e := edges[len(edges)-1].Cursor
		startCursor = &s
		endCursor = &e
	}
	total, _ := r.cols.Products.CountDocuments(ctx, bson.M{"is_active": true})
	return &model.ProductConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: after != nil && *after != "",
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int(total),
	}, nil
}

// Product returns a single product by ID.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, errNotFound
	}
	var p dbmodel.Product
	if err = r.cols.Products.FindOne(ctx, bson.M{"_id": oid, "is_active": true}).Decode(&p); err != nil {
		return nil, errNotFound
	}
	return &model.Product{
		ID:          p.ID.Hex(),
		Name:        p.Name,
		Description: p.Description,
		Category:    model.ProductCategory(p.Category),
		Price:       p.Price,
		Stock:       p.Stock,
		ThcContent:  p.THCContent,
		CbdContent:  p.CBDContent,
		Strain:      p.Strain,
		Origin:      p.Origin,
		ImageURLs:   p.ImageURLs,
		SellerID:    p.SellerID.Hex(),
		IsActive:    p.IsActive,
		CreatedAt:   p.CreatedAt,
		UpdatedAt:   p.UpdatedAt,
	}, nil
}

// Me returns the currently authenticated user.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	uid, err := primitive.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, errNotFound
	}
	var user dbmodel.User
	if err = r.cols.Users.FindOne(ctx, bson.M{"_id": uid}).Decode(&user); err != nil {
		return nil, errNotFound
	}
	return toGraphUser(user), nil
}

// MyOrders returns orders belonging to the authenticated user.
func (r *queryResolver) MyOrders(ctx context.Context) ([]*model.Order, error) {
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	buyerID, _ := primitive.ObjectIDFromHex(claims.UserID)
	cursor, err := r.cols.Orders.Find(ctx, bson.M{"buyer_id": buyerID})
	if err != nil {
		return nil, errInternal
	}
	defer cursor.Close(ctx)
	var dbOrders []dbmodel.Order
	if err = cursor.All(ctx, &dbOrders); err != nil {
		return nil, errInternal
	}
	return r.toGraphOrders(ctx, dbOrders)
}

// Order returns a single order by ID.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	claims, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, errNotFound
	}
	filter := bson.M{"_id": oid}
	if hasRole(claims.Roles, model.UserRoleCustomer) && !hasRole(claims.Roles, model.UserRoleAdmin) {
		buyerID, _ := primitive.ObjectIDFromHex(claims.UserID)
		filter["buyer_id"] = buyerID
	}
	var dbOrder dbmodel.Order
	if err = r.cols.Orders.FindOne(ctx, filter).Decode(&dbOrder); err != nil {
		return nil, errNotFound
	}
	return r.singleOrder(ctx, dbOrder)
}

// SellerProducts returns all products for the authenticated seller.
func (r *queryResolver) SellerProducts(ctx context.Context) ([]*model.Product, error) {
	claims, err := middleware.RequireRole(ctx, model.UserRoleSeller, model.UserRoleAdmin)
	if err != nil {
		return nil, err
	}
	sellerID, _ := primitive.ObjectIDFromHex(claims.UserID)
	cursor, err := r.cols.Products.Find(ctx, bson.M{"seller_id": sellerID})
	if err != nil {
		return nil, errInternal
	}
	defer cursor.Close(ctx)
	var dbProducts []dbmodel.Product
	if err = cursor.All(ctx, &dbProducts); err != nil {
		return nil, errInternal
	}
	products := make([]*model.Product, len(dbProducts))
	for i, p := range dbProducts {
		products[i] = &model.Product{
			ID:          p.ID.Hex(),
			Name:        p.Name,
			Description: p.Description,
			Category:    model.ProductCategory(p.Category),
			Price:       p.Price,
			Stock:       p.Stock,
			ThcContent:  p.THCContent,
			CbdContent:  p.CBDContent,
			Strain:      p.Strain,
			Origin:      p.Origin,
			ImageURLs:   p.ImageURLs,
			SellerID:    p.SellerID.Hex(),
			IsActive:    p.IsActive,
			CreatedAt:   p.CreatedAt,
			UpdatedAt:   p.UpdatedAt,
		}
	}
	return products, nil
}

// AllOrders returns all orders (admin only).
func (r *queryResolver) AllOrders(ctx context.Context, status *model.OrderStatus) ([]*model.Order, error) {
	if _, err := middleware.RequireRole(ctx, model.UserRoleAdmin); err != nil {
		return nil, err
	}
	query := bson.M{}
	if status != nil {
		query["status"] = string(*status)
	}
	cursor, err := r.cols.Orders.Find(ctx, query)
	if err != nil {
		return nil, errInternal
	}
	defer cursor.Close(ctx)
	var dbOrders []dbmodel.Order
	if err = cursor.All(ctx, &dbOrders); err != nil {
		return nil, errInternal
	}
	return r.toGraphOrders(ctx, dbOrders)
}

// Document is the resolver for the document field.
func (r *userResolver) Document(ctx context.Context, obj *model.User) (*string, error) {
	panic(fmt.Errorf("not implemented: Document - document"))
}

// Phone is the resolver for the phone field.
func (r *userResolver) Phone(ctx context.Context, obj *model.User) (*string, error) {
	panic(fmt.Errorf("not implemented: Phone - phone"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func toDBRoles(roles []model.UserRole) []dbmodel.UserRole {
	dbRoles := make([]dbmodel.UserRole, len(roles))
	for i, r := range roles {
		dbRoles[i] = dbmodel.UserRole(r)
	}
	return dbRoles
}
func toGraphRoles(roles []dbmodel.UserRole) []model.UserRole {
	graphRoles := make([]model.UserRole, len(roles))
	for i, r := range roles {
		graphRoles[i] = model.UserRole(r)
	}
	return graphRoles
}
func hasRole(roles []model.UserRole, role model.UserRole) bool {
	for _, r := range roles {
		if r == role {
			return true
		}
	}
	return false
}
func toGraphUser(u dbmodel.User) *model.User {
	user := &model.User{
		ID:        u.ID.Hex(),
		Email:     u.Email,
		Name:      u.Name,
		Roles:     toGraphRoles(u.Roles),
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}
	if u.Address != nil {
		address := toGraphAddress(*u.Address)
		user.Address = &address
	}
	return user
}
func toGraphProduct(p dbmodel.Product) *model.Product {
	return &model.Product{
		ID:          p.ID.Hex(),
		Name:        p.Name,
		Description: p.Description,
		Category:    model.ProductCategory(p.Category),
		Price:       p.Price,
		Stock:       p.Stock,
		ThcContent:  p.THCContent,
		CbdContent:  p.CBDContent,
		Strain:      p.Strain,
		Origin:      p.Origin,
		ImageURLs:   p.ImageURLs,
		SellerID:    p.SellerID.Hex(),
		IsActive:    p.IsActive,
		CreatedAt:   p.CreatedAt,
		UpdatedAt:   p.UpdatedAt,
	}
}

const defaultPageSize = 20

func (r *Resolver) singleOrder(ctx context.Context, dbOrder dbmodel.Order) (*model.Order, error) {
	orders, err := r.toGraphOrders(ctx, []dbmodel.Order{dbOrder})
	if err != nil {
		return nil, err
	}
	return orders[0], nil
}
func (r *Resolver) toGraphOrders(ctx context.Context, dbOrders []dbmodel.Order) ([]*model.Order, error) {
	orders := make([]*model.Order, len(dbOrders))
	productIDs := make(map[string]primitive.ObjectID)
	buyerIDs := make(map[string]primitive.ObjectID)
	for i, dbOrder := range dbOrders {
		orders[i] = toGraphOrder(dbOrder)
		if !dbOrder.BuyerID.IsZero() {
			buyerIDs[dbOrder.BuyerID.Hex()] = dbOrder.BuyerID
		}
		for _, item := range dbOrder.Items {
			if !item.ProductID.IsZero() {
				productIDs[item.ProductID.Hex()] = item.ProductID
			}
		}
	}
	products, err := r.loadProducts(ctx, productIDs)
	if err != nil {
		return nil, err
	}
	buyers, err := r.loadUsers(ctx, buyerIDs)
	if err != nil {
		return nil, err
	}
	for _, order := range orders {
		order.Buyer = buyers[order.BuyerID]
		for _, item := range order.Items {
			item.Product = products[item.ProductID]
		}
	}
	return orders, nil
}
func (r *Resolver) loadProducts(ctx context.Context, ids map[string]primitive.ObjectID) (map[string]*model.Product, error) {
	products := make(map[string]*model.Product, len(ids))
	if len(ids) == 0 {
		return products, nil
	}
	cursor, err := r.cols.Products.Find(ctx, bson.M{"_id": bson.M{"$in": objectIDs(ids)}})
	if err != nil {
		return nil, errInternal
	}
	defer cursor.Close(ctx)
	var dbProducts []dbmodel.Product
	if err = cursor.All(ctx, &dbProducts); err != nil {
		return nil, errInternal
	}
	for i := range dbProducts {
		product := toGraphProduct(dbProducts[i])
		products[product.ID] = product
	}
	return products, nil
}
func (r *Resolver) loadUsers(ctx context.Context, ids map[string]primitive.ObjectID) (map[string]*model.User, error) {
	users := make(map[string]*model.User, len(ids))
	if len(ids) == 0 {
		return users, nil
	}
	cursor, err := r.cols.Users.Find(ctx, bson.M{"_id": bson.M{"$in": objectIDs(ids)}})
	if err != nil {
		return nil, errInternal
	}
	defer cursor.Close(ctx)
	var dbUsers []dbmodel.User
	if err = cursor.All(ctx, &dbUsers); err != nil {
		return nil, errInternal
	}
	for i := range dbUsers {
		user := toGraphUser(dbUsers[i])
		users[user.ID] = user
	}
	return users, nil
}
func objectIDs(ids map[string]primitive.ObjectID) []primitive.ObjectID {
	oids := make([]primitive.ObjectID, 0, len(ids))
	for _, id := range ids {
		oids = append(oids, id)
	}
	return oids
}
func toDBAddress(a model.AddressInput) dbmodel.Address {
	addr := dbmodel.Address{
		Street:       a.Street,
		Number:       a.Number,
		Neighborhood: a.Neighborhood,
		City:         a.City,
		State:        a.State,
		ZipCode:      a.ZipCode,
		Country:      a.Country,
	}
	if a.Complement != nil {
		addr.Complement = *a.Complement
	}
	return addr
}
func toGraphAddress(a dbmodel.Address) model.Address {
	addr := model.Address{
		Street:       a.Street,
		Number:       a.Number,
		Neighborhood: a.Neighborhood,
		City:         a.City,
		State:        a.State,
		ZipCode:      a.ZipCode,
		Country:      a.Country,
	}
	if a.Complement != "" {
		complement := a.Complement
		addr.Complement = &complement
	}
	return addr
}
func toGraphOrder(dbOrder dbmodel.Order) *model.Order {
	items := make([]*model.OrderItem, len(dbOrder.Items))
	for i, item := range dbOrder.Items {
		items[i] = &model.OrderItem{
			ProductID: item.ProductID.Hex(),
			Quantity:  item.Quantity,
			UnitPrice: item.UnitPrice,
			Subtotal:  item.Subtotal,
		}
	}
	return &model.Order{
		ID:                 dbOrder.ID.Hex(),
		BuyerID:            dbOrder.BuyerID.Hex(),
		Items:              items,
		TotalAmount:        dbOrder.TotalAmount,
		Status:             model.OrderStatus(dbOrder.Status),
		ShippingAddress:    toGraphAddress(dbOrder.ShippingAddress),
		TemporalWorkflowID: dbOrder.TemporalWorkflowID,
		PaymentIntentID:    dbOrder.PaymentIntentID,
		CreatedAt:          dbOrder.CreatedAt,
		UpdatedAt:          dbOrder.UpdatedAt,
	}
}
