package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"github.com/dani-zion/ganja-livre/internal/graph/generated"
	"github.com/dani-zion/ganja-livre/internal/graph/model"
	dbmodel "github.com/dani-zion/ganja-livre/internal/model"
)

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// ─── Helper functions ────────────────────────────────────────────────────────

func toDBRoles(roles []model.UserRole) []dbmodel.UserRole {
	dbRoles := make([]dbmodel.UserRole, len(roles))
	for i, r := range roles {
		dbRoles[i] = dbmodel.UserRole(r)
	}
	return dbRoles
}

func toGraphRoles(roles []dbmodel.UserRole) []model.UserRole {
	graphRoles := make([]model.UserRole, len(roles))
	for i, r := range roles {
		graphRoles[i] = model.UserRole(r)
	}
	return graphRoles
}

func hasRole(roles []model.UserRole, role model.UserRole) bool {
	for _, r := range roles {
		if r == role {
			return true
		}
	}
	return false
}

func toGraphUser(u dbmodel.User) *model.User {
	user := &model.User{
		ID:        u.ID.Hex(),
		Email:     u.Email,
		Name:      u.Name,
		Roles:     toGraphRoles(u.Roles),
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}
	if u.Address != nil {
		address := toGraphAddress(*u.Address)
		user.Address = &address
	}
	return user
}

func toGraphProduct(p dbmodel.Product) *model.Product {
	return &model.Product{
		ID:          p.ID.Hex(),
		Name:        p.Name,
		Description: p.Description,
		Category:    model.ProductCategory(p.Category),
		Price:       p.Price,
		Stock:       p.Stock,
		ThcContent:  p.THCContent,
		CbdContent:  p.CBDContent,
		Strain:      p.Strain,
		Origin:      p.Origin,
		ImageURLs:   p.ImageURLs,
		SellerID:    p.SellerID.Hex(),
		IsActive:    p.IsActive,
		CreatedAt:   p.CreatedAt,
		UpdatedAt:   p.UpdatedAt,
	}
}
